formatter: "markdown table"

header-from: .header.md

sections:
  hide:
    - modules
    - requirements

content: |-
  {{ .Header }}

  Here is an example of how this module could be used:
  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```  

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

sort:
  by: required

output:
  file: "README.md"
  mode: replace
