name: Generate Terraform docs
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  tfdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: terraform-docs/gh-actions@v1
        with:
          git-push: true
